import '../../node_modules/jquery/dist/jquery.min.js'
import '../../node_modules/tether/dist/js/tether.min.js'
import '../../node_modules/bootstrap/dist/js/bootstrap.min.js'
import '../../node_modules/bootstrap/dist/css/bootstrap.min.css'
import '../css/main.css'
